### ISSUE TITLE
Too many PROM reads

### ISSUE THREAD

**Issue by rcrouthamel** [TEConnectivity/MS5637_Generic_C_Driver#2]
Per the datasheet, there are only 7 PROM registers (0 thru 6). 

"#define MS5637_COEFFICIENT_NUMBERS" should be 7, not 8.
"#define MS5637_PROM_ADDRESS_READ_ADDRESS_7 0xAE" is unnecessary.

Reading the extra address will return an Address NACK which could cause errors during integration.

**Comment by williammarkezana** [comment]
Agreed, CRC implementation was incorrect, thanks again Rob!

**Comment by rcrouthamel** [comment]
No problem, thanks for correcting!
